default_language_version:
    python: python3.11
default_stages:
    - commit
    - push
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-added-large-files
-   repo: local
    hooks:
        - id: isort
          name: isort
          entry: poetry run isort .
          language: python
          args: []
          always_run: true
          pass_filenames: false
        - id: black
          name: black
          entry: poetry run black .
          language: python
          args: []
          always_run: true
          pass_filenames: false
        - id: flake8
          name: flake8
          entry: poetry run flake8
          language: python
          args: []
          always_run: true
          pass_filenames: false
        - id: pyright
          name: pyright
          entry: poetry run pyright
          language: python
          args: []
          always_run: true
          pass_filenames: false
        - id: pytest
          name: pytest
          entry: poetry run pytest
          language: python
          args: []
          stages: [push]
          always_run: true
          pass_filenames: false
