version: '3'

volumes:
  redis_cache: {}
  celery_task: {}

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  gym:
    restart: always
    image: ""
    container_name: gym
    command:
      - bash
      - -c
      - |
        chmod +x /wait-for-it.sh
        /wait-for-it.sh db:3306 -t 20
        python manage.py makemigrations
        python manage.py migrate
        python get_token.py
        python school_insert.py
    env_file:
      - .env.prod
      - .env
    depends_on:
      - redis
    networks:
      - backend
    links:
      - redis
  celery-worker:
    restart: always
    image: ""
    container_name: celery-worker
    command:
      - bash
      - -c
      - |
        celery -A gym worker -l info -P gevent
    env_file:
      - .env.prod
      - .env
    depends_on:
      - redis
      - gym
    networks:
      - backend
  celery-beat:
    restart: always
    image: ""
    container_name: celery-beat
    command:
      - bash
      - -c
      - |
        celery -A gym beat -l info
    env_file:
      - .env.prod
      - .env
    depends_on:
      - redis
      - gym
      - celery-worker
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
